repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-symlinks
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-ast
      - id: check-builtin-literals
      # - id: check-docstring-first

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff # Run the linter.
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format # Run the formatter.
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.1"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --config-file, .mypy.ini]
        # additional_dependencies: [types-redis,types-PyYAML,types-Pygments]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.33.3"
    hooks:
      - id: check-github-workflows
      - id: check-readthedocs

  - repo: https://github.com/kynan/nbstripout
    rev: "0.8.1"
    hooks:
      - id: nbstripout
